### ISSUE TITLE
c# AuthentificateHost

### ISSUE THREAD

**Issue by FranjoMlakar** [islog/liblogicalaccess#106]
Is there a way to specify the HostMode like in c++ function?

c# function:
AuthentificateHost(keyNo, KEY)

c++ function
AuthentificateHost(KEY, keyNo, HostMode)

**Comment by Maxhy** [comment]
I'm not sure what you are talking about, C++ function doesn't have HostMode parameter neither. Could you details with github line code link?
Btw there is a typo here, function should be renamed to AuthenticatHost on a further release.

**Comment by FranjoMlakar** [comment]
Sorry, my bad. It seems i have some altered source code. In my case there is a function 
`void SAMAV2ISO7816Commands::authentificateHost(std::shared_ptr<DESFireKey> key, unsigned char keyno, HostMode ihostmode)`

**Comment by Maxhy** [comment]
Ok good to know.
I believe you are doing right, but don't forget to respect [LGPL license](https://github.com/islog/liblogicalaccess/blob/master/LICENSE.LGPL.txt) about source code modification, program publication and referenced libraries on your program copyright notice. Thanks.

**Comment by FranjoMlakar** [comment]
Don't worry. I'm just trying to learn how all this things are working. Will respect the LGPL license. Thanks for your answer. 
best regards,
