### ISSUE TITLE
DESFireProfile missing

### ISSUE THREAD

**Issue by cxminer** [islog/liblogicalaccess#116]
I was trying to replicate C code into C# from [MIFARE SAM AV1 AV2 examples](https://github.com/islog/liblogicalaccess/wiki/MIFARE-SAM-AV1-AV2-examples), but I noticed that at the end of that page there is a call `std::dynamic_pointer_cast<logicalaccess::DESFireProfile>(chip->getProfile())->setKey(0x521, 1, key);` but class `DESFireProfile` is missing from my LibLogicalAccess library (version 1.85.0.0). I got the library from [LibLogicalAccess Releases](https://github.com/islog/liblogicalaccess/releases). I also fired up `Object Browser`, typed in `DESFireProfile` and I got no results. Where is this class located? Or is there a different approach in C#?

**Comment by Maxhy** [comment]
Indeed `Profile` was removed from latest liblogicalaccess versions. You should directly pass the key object to the `authenticate` command.
