### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by TheAifam5** [islog/liblogicalaccess#122]
Hey,
Which naming convention you using???
I see actually: under_score, camelCase, PascalCase

Can you decide to use one, not 30?

Regards, Mateusz

**Comment by Maxhy** [comment]
Such comments are so much appreciated! Should I say thanks?

It's probably because the library is 8 years old with several contributors (even before it was made public). You're right that only one code convention should be used but there is way to say it. Anyway...
