### ISSUE TITLE
failed in maven build

### ISSUE THREAD

**Issue by bondhan** [islog/liblogicalaccess#134]
Hi,

Is this project still active? I found difficulties to build the source code and stumbled on maven error below:

[ERROR] Failed to execute goal on project liblogicalaccess: Could not resolve dependencies for project eu.islog.lib.readers:liblogicalaccess:pom:1.85.0: The following artifacts could not be resolved: lib.portable:boost:zip:1.57-light2, lib.crypto:openssl:zip:1.0.0b.2, lib.readers:scardsyn:zip:2.0.0.0, lib.readers:rfideas:zip:7.1.5: Could not find artifact lib.portable:boost:zip:1.57-light2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

Do you have any advice?

**Comment by Liryna** [comment]
Hi @bondhan ,

You need to add islog maven repository to your settings
https://github.com/islog/liblogicalaccess/wiki/Build-Liblogicalaccess#maven-installation

**Comment by Maxhy** [comment]
Closing as invalid.
