### ISSUE TITLE
PKCS#11 Key Storage

### ISSUE THREAD

**Issue by Maxhy** [islog/liblogicalaccess#153]
We should create a new PKCS#11 Key Storage as an alternative to IKS Key Storage.

It would not support all DESFire scope (eg: key usage control for authentication / change key, ...) but would be a standard approach for HSM, without the need to provide an ISLOG Key Server module.

HSM are generally compliant with PKCS#11, OpenSSL, JCA/JCE and/or CryptoAPI. One API compatibility should be enough for now and PKCS#11 is the more technology independent one.

For those willing to make a test without buying any hardware, use a software HSM. One provided by OpenDNSSEC group for instance: https://wiki.opendnssec.org/display/SoftHSMDOCS/SoftHSM+Documentation+v2 / https://github.com/opendnssec/SoftHSMv2.git

**Comment by xaqq** [comment]
This has been implemented.
