### ISSUE TITLE
Compile error under Ubuntu 16.04 amd64

### ISSUE THREAD

**Issue by xvoidee** [islog/liblogicalaccess#158]
Hi,

When I try to build library on Ubuntu 16, I always get following error at the end:

`[ 82%] Built target rplethreaders
[ 83%] Built target scielreaders
[ 85%] Built target smartidreaders
[ 87%] Built target stidstrreaders
[ 89%] Built target stidprgreaders
[ 90%] Built target lla-tests
[ 90%] Linking CXX executable desfireev1_test_general
../../../plugins/pluginsreaderproviders/pcsc/libpcscreaders.so.1.85.0: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
../../../plugins/pluginsreaderproviders/pcsc/libpcscreaders.so.1.85.0: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
tests/pcsc-tests/DESFireEV1/CMakeFiles/desfireev1_test_general.dir/build.make:133: recipe for target 'tests/pcsc-tests/DESFireEV1/desfireev1_test_general' failed
make[2]: *** [tests/pcsc-tests/DESFireEV1/desfireev1_test_general] Error 1
CMakeFiles/Makefile2:3079: recipe for target 'tests/pcsc-tests/DESFireEV1/CMakeFiles/desfireev1_test_general.dir/all' failed
make[1]: *** [tests/pcsc-tests/DESFireEV1/CMakeFiles/desfireev1_test_general.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

System info:

`foobar@lol:build$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
foobar@lol:build$ uname -a
Linux lol 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Liryna** [comment]
hi @xvoidee ,

seems like you are missing some dependancy boost.
