### ISSUE TITLE
 LibLogicalAccess 1.81.0 for KeePassRFID plugin

### ISSUE THREAD

**Issue by kaczorws** [islog/liblogicalaccess#197]
Hello,

Is there a way to download compiled windows binaries for version 1.81.0? It seems all download links were taken down and no longer available. I wanted to use that specific version for the KeePassRFID plugin but I have trouble compiling it, probably due to different version of Visual Studio (1.81.0 suggests that older version should be used).

The original link was:
http://artifacts.islog.com/repository/rfid-releases/eu/islog/lib/readers/liblogicalaccess-exe/1.81.0/liblogicalaccess-exe-1.81.0.zip

Alternatively, can anyone share just the DLLs required for KeePassRFID? Thanks

**Comment by Maxhy** [comment]
See https://github.com/islog/keepassrfid/issues/4
