### ISSUE TITLE
changeKey() Problem in COM Wrapper?!

### ISSUE THREAD

**Issue by c3rebro** [islog/liblogicalaccess#205]
Hello,

i currently face the same problem as in #99.

@Liryna: You mean that you were only able to reproduce the error when you force a wrong key version right? I let the keyversion untouched (= 0).

I would like to change one of the keys in the application twice. I get an CRC/CMAC error like in #99 when i try to change it for the second time.

I tried to set the Keysettings to allow_change_with_MK. This will lead to the error above.

If i set the Keysettinigs to allow_change_key_using_keyNo on the other hand i can change the Key multiple times without errors.

**Comment by Liryna** [comment]
Hi @c3rebro ,

It has been a while for me and forgot the exact details here. Sorry for not being able to be more helpful.

**Comment by c3rebro** [comment]
this issue does no longer occur in 2.4.0
