### ISSUE TITLE
DESFire EV2

### ISSUE THREAD

**Issue by Maxhy** [islog/liblogicalaccess#3]
NXP is launching Mifare DESFire EV2 chip this year. Adding its support into the library is important.
Dedicated wiki page with technical information about the Mifare DESFire EV2 specification: http://liblogicalaccess.islog.com/wiki/doku.php/mifare-desfire-ev2-examples

**Comment by scharada** [comment]
any updates on this Item ? the EV2 shipped last year ...

**Comment by Liryna** [comment]
@scharada The EV2 was released some month ago. Not shipped last year

**Comment by Dizgah** [comment]
Is there any program to supporting EV2 cards?

**Comment by Liryna** [comment]
DESFire EV2 is a closed source plugin currently. See https://github.com/islog/liblogicalaccess/wiki/Install-LibLogicalAccess#see-also

**Comment by Dizgah** [comment]
In the mentioned link there are nothing about Desfire EV2 especially,
As I know confidential rules are same for Desfire EV1 & Desfire EV2,then why one of them supported in open source library and the other one not ?

**Comment by Liryna** [comment]
@Dizgah We will let the EV2 as closed source for now to motivate companies using the library to support it. It will be move to open-source when the EV2 will be used by the public into some years. 

EV2 took time to make, I think you can understand that it deserves some support. 

If you have another idea how the library can get support without having desfire as closed source feel free.

**Comment by Liryna** [comment]
NXP DESFireEV2 MF3Dx2 ISO7816 has been implemented with full features and Secure Messaging 
See
https://github.com/islog/liblogicalaccess/commit/8a249c6efa5cde62df3ad339a76d979fc8fb12a3
https://github.com/islog/liblogicalaccess/commit/29528ef7b5b2ba33e34899207158478219d61dd8

**Comment by Dizgah** [comment]
Really thank you for this commit,Does this commit support special features of EV2(e.g. multi-application solutions) ?

**Comment by Liryna** [comment]
DESFireEV2 with EV2 Authentication now support SAM AV2 authentication.
Changekey with SAM cannot be used currently because of SAM AV2 crypto limitations.
We will need to wait AV3 to make it happen.

**Comment by Liryna** [comment]
This can now be closed. 
Added to supported hardware https://github.com/islog/liblogicalaccess/wiki/Supported-hardware
