### ISSUE TITLE
Implement NFC Tag as a Card Service

### ISSUE THREAD

**Issue by Maxhy** [islog/liblogicalaccess#5]
NFC Tag can be easily implemented into the core as a new card service.
Specification is well documented and it is not complicated to do. We should do it.

**Comment by Liryna** [comment]
We should be able to put the tag in READ ONLY
https://github.com/islog/liblogicalaccess/blob/master/plugins/pluginscards/iso7816/iso7816nfctag4cardservice.cpp#L35

**Comment by Maxhy** [comment]
Also, adding support for NFC Type Mifare Classic Tag
http://www.nxp.com/documents/application_note/AN1305.pdf

**Comment by Maxhy** [comment]
NFC Tag Type 1, 2, 3 and Mifare Classic compatibility added.
Multiple NDEF messages, chunked records and lock features will not be supported unless on specific request.
