### ISSUE TITLE
How to access all the chip locations properly

### ISSUE THREAD

**Issue by madwyn** [islog/liblogicalaccess#64]
I would like to access any location of the chip using a generic way.

I read the following code from [here](http://liblogicalaccess.islog.com/wiki/doku.php/api-how-to-examples):

> Iterate the chip memory areas

```c
// Get the root node
boost::shared_ptr<logicalaccess::LocationNode> rootNode = chip->getRootLocationNode();
// Get childrens of this node
std::vector<boost::shared_ptr<logicalaccess::LocationNode> > childs = rootNode->getChildrens();
for (std::vector<boost::shared_ptr<logicalaccess::LocationNode> >::iterator i = childs.begin(); i != childs.end(); ++i)
{
  // Display node information
  std::cout << "Size of node " << (*i)->getName() << ": " << ((*i)->getLength() * (*i)->getUnit()) << " bytes";
 
  // Get the associated location for that node (to read or write data for example)
  boost::shared_ptr<logicalaccess::Location> childlocation = (*i)->getLocation();
}
```

This leaves me the problem of how to access all the memory areas.

For example, Mifare1K will get the `childs` vector size of 16, each has 48 bytes. But the chip has 16 sectors and 3 blocks for each sector.

`(*i)->getLocation()` will only be able to access the 0th block of each sector. How do I skip the 0th block of sector 0? How do I access the rest?

I have tried to `getChildrens()` from `(*i)` but the vector has nothing in it.

**Would you please show me the proper way of accessing any block in a generic way?**

Because my application reads/writes different chips in a consecutive manner, it requires generic r/w functions. The chips are generated using factory pattern.

I'm currently using a hack to do this:

I just changed the inherited classes of Location to virtual, for example:

`class LIBLOGICALACCESS_API MifareLocation : public Location`
`class LIBLOGICALACCESS_API MifareLocation : public virtual Location`

> Create another generic accessing concrete class:

```c++
class ChipLocation : public virtual Location {
public:
    virtual void   reset(void) = 0;
    virtual void   forward(int step) {
        for (int i = 0; i < step; ++i) {
            next();
        }
    }
    virtual void   next(void)  = 0; // to access the next area
    virtual bool   isEOF(void) = 0; // is the END
    virtual size_t step_size(void)  = 0; // the bytes per step

    virtual size_t maxDataLen(void) = 0;
};
```

> Extend the class and implement the functions:

```c++
class ChipLocationMifareClassic1K : public ChipLocation, public logicalaccess::MifareLocation
```

> Use `ChipLocationMifareClassic1K` instead of `MifareLocation`.

> Loop the locations as below:

```c++
int loc_step = 2;
for (location->reset(); !location->isEOF(); location->forward(loc_step)) {
    // access the location directly
    location;
}
```

**Comment by Maxhy** [comment]
Location nodes now have getCanRead() and getCanWrite() methods.
Mifare chip now populate blocks location nodes under sectors location nodes.

I believe this should be enough to match this requirement.
