### ISSUE TITLE
[Mifare Classic] Wrong use of the profile

### ISSUE THREAD

**Issue by Liryna** [islog/liblogicalaccess#68]
For now, keys expected to be used for a "changekey" are stored in the sector "getMifareChip()->getNbSectors()" of the profile.
This is not user friendly !
We should think about having another way to store them.
 
https://github.com/islog/liblogicalaccess/blob/develop/plugins/pluginscards/mifare/mifarecommands.cpp#L320

**Comment by Maxhy** [comment]
Profile logic should be completely removed from liblogicalaccess and handled on high level applications.

**Comment by Maxhy** [comment]
Profile logic was removed with 6ce073684b12f56af3a716d31c8cac8d7c45e931.
