### ISSUE TITLE
Wrong exemples in the wiki

### ISSUE THREAD

**Issue by nimch** [islog/liblogicalaccess#74]
Hello

I think "Read/Write data on the chip" exemple on the wiki is wrong. Indeed, readData/writeData calls are not correct.

Regards.

**Comment by Liryna** [comment]
Yes indeed ! The exemples are not update with the lastest changed.
Need to find time to do it :(

**Comment by Liryna** [comment]
- [x] Documentation moved to github
- [ ] Review content
- [ ] Fix Documentation examples
- [x] Add examples to source repository https://github.com/islog/liblogicalaccess/tree/master/tests
- [ ] Add tests to travis build
