### ISSUE TITLE
Link error windows/visual studio 2013

### ISSUE THREAD

**Issue by nimch** [islog/liblogicalaccess#75]
Hello

I'm trying to build a programme using liblogicalaccess and I can't solve link error.
I have boost 1.57 precompiled installed (lib32-msvc-12.0), openssl 1.0.1j and liblogicalaccess 1.77.1 too.
Compilation is ok but I encounter link error, for exemple : error LNK2019 __declspec(dllimport) public: __thiscall logicalaccess::ReaderConfiguration::ReaderConfiguration(void) in spite of I put lib path in my visual studio solution settings.
Any idea ?

Thanks
Regards

**Comment by Liryna** [comment]
Are you sure you have liblogicalaccess.lib as dependency ?

**Comment by nimch** [comment]
yes

**Comment by Liryna** [comment]
Did you try the basic:
https://github.com/islog/liblogicalaccess/blob/master/samples/basic/
?

**Comment by nimch** [comment]
My test programm is more or less the basic but yes I check again : same link error

**Comment by Liryna** [comment]
I have really no idea :(
I build my windows project exactly like this.
It seems that your Visual Studio is not looking for the symbole inside the liblogicalaccess.
What happen if you remove liblogicalaccess from the path ?

**Comment by nimch** [comment]
With or without liblogicalaccess.lib path give the same link errors.
If I remove lib boost path I have new errors relative to boost so I can conclude this parameter (include) is read...

**Comment by nimch** [comment]
Thank you for your help.
Weekend time.
I will investigate next week.
Bye.

**Comment by Liryna** [comment]
The project use the same architecture as the library in the path ?

**Comment by nimch** [comment]
hello.

Yes, all win32.

**Comment by Liryna** [comment]
"With or without liblogicalaccess.lib path give the same link errors."
it mean that Visual Studio is even not using liblogicalaccess.lib.

You should look on this way

**Comment by Liryna** [comment]
Have you been able to fix the error ?

**Comment by nimch** [comment]
No...
