### ISSUE TITLE
Character set on ASCII field

### ISSUE THREAD

**Issue by Maxhy** [islog/liblogicalaccess#77]
On ASCII field of custom format, add a parameter to define the character set (ASCII, UTF-16, UTF-8, ...).
*ASCII* field will become *String* field btw.

**Comment by Liryna** [comment]
We should template ASCIIDataField with std::string, std::u16string and std::u32string.

**Comment by Maxhy** [comment]
ASCIIField is now StringField with a character set member used to describe the buffer.
