### ISSUE TITLE
Quick question about Desfire Ev2

### ISSUE THREAD

**Issue by clarklight** [islog/liblogicalaccess#93]
I saw a page that says "The chip Mifare DESFire EV2 is not released yet by NXP", and that was edited in June 2015, but the first document about releasing EV2 was in 2013...i am just wondering it is officially out and can be purchased on the market??

**Comment by Liryna** [comment]
It is not officially out for now :( We are still waiting

**Comment by clarklight** [comment]
Thanks.... yer it just seems like its been a while...i got a quick question not sure if you have any experience on it.... with NTAG 21x family, their password protected area, do you think its secure? I read on their documents and some opinion that it is pretty weak. 

I am just trying to figure out for "Anti-cloning" mechanism if NTAG 21x or Desfire would be better.

**Comment by Liryna** [comment]
Well NTAG 21x are not made for security. If someone want to clone it and with a little experience, he can do it.
But as always, it depend of the security you need.

**Comment by clarklight** [comment]
Em.... yer, thats what i was thinking.... i just dont want any card to be cloned. Was planning to have a password protected area that has an account ID hidden within it. and Only when password has been entered correctly then it can be read.

So i guess i will have to go with the Desfire EV1 for now. Thanks for the reply!

**Comment by Liryna** [comment]
No problem :) If you need any other help, feel free to ask !
