### ISSUE TITLE
liblogicalaccess.com.dll failed to register

### ISSUE THREAD

**Issue by AndrewLeiper** [islog/liblogicalaccess#95]
Hi there,

I'm unable to install liblogicalaccess-exe-1.79.0.

The install program gives the message "...liblogicalaccess.com.dll failed to register HRESULT -214024770".
This happens on Windows 7 and Windows 10.

Do you have any ideas on what may be wrong ?

Andy Leiper

**Comment by Maxhy** [comment]
Indeed, the correct release file is http://artifacts.islog.com/repository/rfid-releases/eu/islog/lib/readers/liblogicalaccess-exe/1.79.1/liblogicalaccess-exe-1.79.1.zip
I will update the release link, thanks!
