### ISSUE TITLE
Desfire Ev1 create file followed by delete file causes "Wrong CMAC"

### ISSUE THREAD

**Issue by xaqq** [islog/liblogicalaccess#97]
Calling `cmdev1->createStdDataFile(0x04, logicalaccess::EncryptionMode::CM_ENCRYPT, ar, file_size, 0)` followed by `cmdev1->deleteFile(0x04)` causes Logicalaccess to throw "Wrong CMAC".

However, both operation complete successfully despite the exception being thrown.

A workaround is to call  `authenticate(0, key)` between those 2 calls.

**Comment by xaqq** [comment]
Same problem happens when trying to change a key after creating a file: `cmd->changeKey(0, new_key);`

However, creating two files seems to work fine.

**Comment by Maxhy** [comment]
Fixed with ba19be5b419365fce125faa92a9a6192787d67d2.
